import 'package:construculator/libraries/auth/data/types/auth_types.dart';

/// Represents a user in the application
class User {
  /// The unique identifier for the user, generated by the auth.users/credentials table
  final String id;

  /// The unique identifier for the user's credential, generated by the auth.users/credentials table
  final String credentialId;

  /// The email of the user
  final String email;

  /// The phone number of the user
  final String? phone;

  /// The first name of the user
  final String firstName;

  /// The last name of the user
  final String lastName;

  /// The professional role of the user
  final String professionalRole;

  /// The URL of the user's profile photo
  final String? profilePhotoUrl;

  /// The date and time the user was created
  final DateTime createdAt;

  /// The date and time the user was last updated
  final DateTime updatedAt;

  /// The status of the user, currently active or inactive.
  final UserProfileStatus userStatus;

  /// A map of user preferences, currently empty.
  final Map<String, dynamic> userPreferences;

  User({
    required this.id,
    required this.credentialId,
    required this.email,
    this.phone,
    required this.firstName,
    required this.lastName,
    required this.professionalRole,
    this.profilePhotoUrl,
    required this.createdAt,
    required this.updatedAt,
    required this.userStatus,
    required this.userPreferences,
  });

  /// Used to create a user from a JSON object
  factory User.fromJson(Map<String, dynamic> json) {
    return User(
      id: json['id'] as String,
      credentialId: json['credential_id'] as String,
      email: json['email'] as String,
      phone: json['phone'] as String?,
      firstName: json['first_name'] as String,
      lastName: json['last_name'] as String,
      professionalRole: json['professional_role'] as String,
      profilePhotoUrl: json['profile_photo_url'] as String?,
      createdAt: DateTime.parse(json['created_at'] as String),
      updatedAt: DateTime.parse(json['updated_at'] as String),
      userStatus: json['user_status'] == 'active' ? UserProfileStatus.active : UserProfileStatus.inactive ,
      userPreferences: json['user_preferences'] as Map<String, dynamic>,
    );
  }

  /// Used to convert the user to a JSON object
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'credential_id': credentialId,
      'email': email,
      'phone': phone,
      'first_name': firstName,
      'last_name': lastName,
      'professional_role': professionalRole,
      'profile_photo_url': profilePhotoUrl,
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
      'user_status': userStatus.toString().split('.').last,
      'user_preferences': userPreferences,
    };
  }

  /// Used to create an empty user
  static User empty() {
    return User(
      id: '',
      credentialId: '',
      email: '',
      phone: '',
      firstName: '',
      lastName: '',
      professionalRole: '',
      profilePhotoUrl: '',
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
      userStatus: UserProfileStatus.inactive,
      userPreferences: {},
    );
  }

  /// The full name of the user, computed from the first and last name
  String get fullName => '$firstName $lastName';
  
  /// Used to create a copy of the user with modified properties
  User copyWith({
    String? id,
    String? credentialId,
    String? email,
    String? phone,
    String? firstName,
    String? lastName,
    String? professionalRole,
    String? profilePhotoUrl,
    DateTime? createdAt,
    DateTime? updatedAt,
    UserProfileStatus? userStatus,
    Map<String, dynamic>? userPreferences,
  }) {
    return User(
      id: id ?? this.id,
      credentialId: credentialId ?? this.credentialId,
      email: email ?? this.email,
      phone: phone ?? this.phone,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      professionalRole: professionalRole ?? this.professionalRole,
      profilePhotoUrl: profilePhotoUrl ?? this.profilePhotoUrl,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      userStatus: userStatus ?? this.userStatus,
      userPreferences: userPreferences ?? this.userPreferences,
    );
  }
}