workflows:
  pre-check:
    name: Pre-check
    instance_type: linux_x2
    environment:
      groups:
        - notification_emails
      flutter: 3.29.2
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: false
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
        - ios/Pods
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Block skip-checks
        script: |
          # Fail if commit message contains "[skip ci]"
          if git log -1 --pretty=%B | grep -Eq "\[skip ci\]|\[ci skip\]"; then
            echo "❌ Skipping checks is not allowed!"
            exit 1
          fi
      - name: Clone and Checkout
        script: |
          git clone "$CM_REPO_URL" .
          git checkout "$CM_COMMIT"

      - name: Install Dependencies
        script: |
          flutter pub get

      - name: Run Code Analysis
        script: |
          echo "Linux version: $(uname -a)"
          echo "Triggered By: $CM_BUILD_STARTED_BY"
          echo "🛠️ Running Flutter analysis..."
          # Get the base commit (when the PR branched off the target branch)
          BASE_COMMIT=$(git merge-base HEAD origin/$CM_PULL_REQUEST_DEST)

          # Identify changed Dart files (lib/ and test/)
          CHANGED_DART_FILES=$(git diff --name-only  --diff-filter=d $BASE_COMMIT HEAD -- "lib/*.dart" "test/*.dart")

          if [ -z "$CHANGED_DART_FILES" ]; then
            echo "✅ No Dart files modified. Skipping analysis."
            exit 0
          fi
          echo "🛠️ Analyzing changed files:"
          echo "$CHANGED_DART_FILES"
          flutter analyze --fatal-infos --fatal-warnings $CHANGED_DART_FILES

      - name: Run Unit Tests With Coverage
        script: |
          # Find the common ancestor commit between source and target branches
          BASE_COMMIT=$(git merge-base HEAD origin/$CM_PULL_REQUEST_DEST)

          # Get changed test files since branching from target
          CHANGED_TESTS=$(git diff --name-only  --diff-filter=d $BASE_COMMIT HEAD -- "test/units/*.dart")

          if [ -z "$CHANGED_TESTS" ]; then
            echo "✅ No test files modified. Skipping tests..."
            exit 0
          fi
          echo "🔍 Running tests for changed files:"
          echo "$CHANGED_TESTS"
          TARGET=$ARC_CODE_COVERAGE_TARGET
          if git log -1 --pretty=%B | grep -Eq "#DeltaCoverageLow|DCL"; then
            TARGET=$CODE_COVERAGE_MINIMUM
            echo "Using minimum coverage target: ${TARGET}% "
          fi
          HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
          mkdir -p test-results
          flutter test $CHANGED_TESTS --coverage --machine > test-results/flutter.json

          # Compute coverage
          if [ ! -f "coverage/lcov.info" ] || [ ! -s "coverage/lcov.info" ]; then
            echo "❌ Coverage file coverage/lcov.info is missing or empty."
            exit 1
          fi

          LF_RAW=$(grep '^LF:' coverage/lcov.info | cut -d: -f2 || true)
          LH_RAW=$(grep '^LH:' coverage/lcov.info | cut -d: -f2 || true)

          if [ -z "$LF_RAW" ]; then
              LF_SUM=0
          else
              LF_SUM=$(echo "$LF_RAW" | awk '{sum+=$1} END {print sum}')
          fi

          if [ -z "$LH_RAW" ]; then
              LH_SUM=0
          else
              LH_SUM=$(echo "$LH_RAW" | awk '{sum+=$1} END {print sum}')
          fi
          
          if ! [[ "$LF_SUM" =~ ^[0-9]+$ ]]; then
              echo "❌ LF_SUM ($LF_SUM) is not a valid number. Cannot calculate coverage."
              exit 1
          fi
          if ! [[ "$LH_SUM" =~ ^[0-9]+$ ]]; then
              echo "⚠️ LH_SUM ($LH_SUM) is not a valid number. Assuming 0 lines hit for calculation."
              LH_SUM=0
          fi

          if [ "$LF_SUM" -eq 0 ]; then
            COVERAGE_PERCENT="0.00"
            echo "⚠️ LF (total lines found) is 0. Setting coverage to 0.00%."
          else
            COVERAGE_PERCENT=$(echo "scale=2; $LH_SUM*100/$LF_SUM" | bc)
          fi

          echo "Code Coverage: ${COVERAGE_PERCENT}%"

          if (( $(echo "$COVERAGE_PERCENT < $TARGET" | bc -l) )); then
            echo "❌ Coverage is $COVERAGE_PERCENT%, below $TARGET%"
            exit 1
          else
            echo "✅ Coverage is $COVERAGE_PERCENT% (>= $TARGET%)"
          fi
        test_report: test-results/flutter.json
      - name: Run Changed Tests
        script: |
          # Find the common ancestor commit between source and target branches
          BASE_COMMIT=$(git merge-base HEAD origin/$CM_PULL_REQUEST_DEST)
          
          # Get changed test files since branching from target
          CHANGED_TESTS=$(git diff --name-only  --diff-filter=d $BASE_COMMIT HEAD -- "test/*.dart")
          
          if [ -z "$CHANGED_TESTS" ]; then
            echo "✅ No test files modified. Skipping tests..."
            exit 0
          fi
          echo "🔍 Running tests for changed files:"
          echo "$CHANGED_TESTS"
          flutter test $CHANGED_TESTS --exclude-tags=units
    publishing:
      email:
        recipients:
          - $EMAIL_DANIEL
        notify:
          success: true
          failure: true
      slack:
        channel: '#build-notifications'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
  comprehensive-check:
    name: Comprehensive Check
    instance_type: linux_x2
    environment:
      groups:
        - notification_emails
        - ripple_arc
      flutter: 3.29.2
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Clone and Checkout
        script: |
          git clone $CM_REPO_URL .
          git checkout $CM_COMMIT

      - name: Install Dependencies
        script: |
          flutter pub get

      - name: Run Code Analysis
        script: |
          echo "🛠️ Running Flutter analysis..."
          flutter analyze --fatal-infos --fatal-warnings .

      - name: Run Unit Tests With Coverage Report
        script: |
          TARGET=$ARC_CODE_COVERAGE_TARGET
          if git log -1 --pretty=%B | grep -Eq "#DeltaCoverageLow|DCL"; then
            TARGET=$CODE_COVERAGE_MINIMUM
            echo "Using minimum coverage target: ${TARGET}% "
          fi
          sudo apt-get install -y lcov
          mkdir -p test-results
          flutter test test/units --coverage --machine > test-results/flutter.json
          
          # Compute coverage
          if [ ! -f "coverage/lcov.info" ] || [ ! -s "coverage/lcov.info" ]; then
            echo "❌ Coverage file coverage/lcov.info is missing or empty."
            exit 1
          fi

          LF_RAW=$(grep '^LF:' coverage/lcov.info | cut -d: -f2 || true)
          LH_RAW=$(grep '^LH:' coverage/lcov.info | cut -d: -f2 || true)

          if [ -z "$LF_RAW" ]; then
              LF_SUM=0
          else
              LF_SUM=$(echo "$LF_RAW" | awk '{sum+=$1} END {print sum}')
          fi

          if [ -z "$LH_RAW" ]; then
              LH_SUM=0
          else
              LH_SUM=$(echo "$LH_RAW" | awk '{sum+=$1} END {print sum}')
          fi

          if ! [[ "$LF_SUM" =~ ^[0-9]+$ ]]; then
              echo "❌ LF_SUM ($LF_SUM) is not a valid number. Cannot calculate coverage."
              exit 1
          fi
          if ! [[ "$LH_SUM" =~ ^[0-9]+$ ]]; then
              echo "⚠️ LH_SUM ($LH_SUM) is not a valid number. Assuming 0 lines hit for calculation."
              LH_SUM=0
          fi

          if [ "$LF_SUM" -eq 0 ]; then
            COVERAGE_PERCENT="0.00"
            echo "⚠️ LF (total lines found) is 0. Setting coverage to 0.00%."
          else
            COVERAGE_PERCENT=$(echo "scale=2; $LH_SUM*100/$LF_SUM" | bc)
          fi
          
          echo "Code Coverage: ${COVERAGE_PERCENT}%"
          
          if (( $(echo "$COVERAGE_PERCENT < $TARGET" | bc -l) )); then
            echo "❌ Coverage is $COVERAGE_PERCENT%, below $TARGET%"
            exit 1
          else
            echo "✅ Coverage is $COVERAGE_PERCENT% (>= $TARGET%)"
          fi
        test_report: test-results/flutter.json

      - name: Run Widget Tests
        script: |
          flutter test test/widgets

      - name: Run Screenshot Tests
        script: |
          flutter test test/screenshots

      - name: Mutation Testing
        script: |
          BASE_COMMIT=$(git merge-base HEAD origin/$BASE_BRANCH)
          
          echo "🧬 Running mutation tests..."
          # Get changed mutation config files from test/mutations/
          CHANGED_MUTATION_CONFIGS=$(git diff --name-only --diff-filter=d "$BASE_COMMIT" HEAD -- "test/mutations/*.xml")
          
          if [ -z "$CHANGED_MUTATION_CONFIGS" ]; then
            echo "✅ No changed mutation config files (test/mutations/*.xml) detected. Skipping mutation tests."
            exit 0
          else
            echo "Found changed mutation config files:"
            echo "$CHANGED_MUTATION_CONFIGS"
            FAILED_MUTATION_TESTS=0
            # Ensure IFS is set to newline for the loop to handle filenames with spaces correctly, though git diff usually doesn't produce them.
            OLD_IFS="$IFS"
            IFS=$'\n'
            for CONFIG_FILE in $CHANGED_MUTATION_CONFIGS; do
              IFS="$OLD_IFS" # Restore IFS for commands within the loop
              echo "🏃 Running mutation test with config: $CONFIG_FILE"
              if ! dart run mutation_test "$CONFIG_FILE" --no-builtin; then
                echo "❌ Mutation test failed for config: $CONFIG_FILE"
                FAILED_MUTATION_TESTS=$((FAILED_MUTATION_TESTS + 1))
              else
                echo "✅ Mutation test passed for config: $CONFIG_FILE"
              fi
              IFS=$'\n' # Re-set IFS for the next iteration
            done
            IFS="$OLD_IFS" # Restore IFS after the loop

            if [ "$FAILED_MUTATION_TESTS" -gt 0 ]; then
              echo "❌ $FAILED_MUTATION_TESTS mutation test(s) failed."
              exit 1
            else
              echo "✅ All mutation tests passed."
            fi
          fi

      - name: Build Android Debug
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - coverage/*
      - test-results/flutter.json
      - mutation-test-report/*
    publishing:
      email:
        recipients:
          - $EMAIL_DANIEL
        notify:
          success: true
          failure: true
      slack:
        channel: '#build-notifications'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
  periodic-check:
    name: Periodic Check
    instance_type: linux_x2
    environment:
      groups:
        - notification_emails
        - ripple_arc
      flutter: 3.29.2
      ubuntu: 24.04
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
        - ios/Pods
        - $FLUTTER_ROOT/.pub-cache
        - /usr/local/Homebrew
        - /usr/local/bin/lcov
    scripts:
      - name: Clone and Checkout
        script: |
          git clone $CM_REPO_URL .
          git checkout $BASE_BRANCH

      - name: Install Dependencies
        script: |
          echo "Downloading Dependencies..."
          flutter pub get

      - name: Run Code Analysis
        script: |
          echo "🛠️ Running Flutter analysis..."
          flutter analyze --fatal-infos --fatal-warnings .

      - name: Run Unit Tests With Coverage Report
        script: |
          TARGET=$ARC_CODE_COVERAGE_TARGET
          if git log -1 --pretty=%B | grep -Eq "#DeltaCoverageLow|DCL"; then
            TARGET=$CODE_COVERAGE_MINIMUM
            echo "Using minimum coverage target: ${TARGET}% "
          fi
          HOMEBREW_NO_AUTO_UPDATE=1 brew install lcov
          mkdir -p test-results
          flutter test --tags=units --coverage --machine > test-results/flutter.json
          
          # Compute coverage
          if [ ! -f "coverage/lcov.info" ] || [ ! -s "coverage/lcov.info" ]; then
            echo "❌ Coverage file coverage/lcov.info is missing or empty."
            exit 1
          fi

          LF_RAW=$(grep '^LF:' coverage/lcov.info | cut -d: -f2 || true)
          LH_RAW=$(grep '^LH:' coverage/lcov.info | cut -d: -f2 || true)

          if [ -z "$LF_RAW" ]; then
              LF_SUM=0
          else
              LF_SUM=$(echo "$LF_RAW" | awk '{sum+=$1} END {print sum}')
          fi

          if [ -z "$LH_RAW" ]; then
              LH_SUM=0
          else
              LH_SUM=$(echo "$LH_RAW" | awk '{sum+=$1} END {print sum}')
          fi

          if ! [[ "$LF_SUM" =~ ^[0-9]+$ ]]; then
              echo "❌ LF_SUM ($LF_SUM) is not a valid number. Cannot calculate coverage."
              exit 1
          fi
          if ! [[ "$LH_SUM" =~ ^[0-9]+$ ]]; then
              echo "⚠️ LH_SUM ($LH_SUM) is not a valid number. Assuming 0 lines hit for calculation."
              LH_SUM=0
          fi

          if [ "$LF_SUM" -eq 0 ]; then
            COVERAGE_PERCENT="0.00"
            echo "⚠️ LF (total lines found) is 0. Setting coverage to 0.00%."
          else
            COVERAGE_PERCENT=$(echo "scale=2; $LH_SUM*100/$LF_SUM" | bc)
          fi

          echo "Code Coverage: ${COVERAGE_PERCENT}%"

          if (( $(echo "$COVERAGE_PERCENT < $TARGET" | bc -l) )); then
            echo "❌ Coverage is $COVERAGE_PERCENT%, below $TARGET%"
            exit 1
          else
            echo "✅ Coverage is $COVERAGE_PERCENT% (>= $TARGET%)"
          fi
        test_report: test-results/flutter.json

      - name: Run Widget Tests
        script: |
          flutter test test/widgets

      - name: Run Screenshot Tests
        script: |
          flutter test test/screenshots

      - name: Mutation Testing
        script: |
          CHANGED_FILES=$(git diff --name-only  --diff-filter=d HEAD HEAD~1 | grep -v "^test" | grep ".dart$" | tr '\n' ' ')
          # Check if CHANGED_FILES is empty
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed Dart files detected. Skipping mutation tests."
            exit 0
          else
            echo "Running mutation tests on: $CHANGED_FILES"
            dart run mutation_test $CHANGED_FILES --rules=mutation_test_rules.xml
          fi

      - name: Build Android Debug
        script: |
          flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa
      - coverage/*
      - test-results/flutter.json
      - mutation-test-report/*
    publishing:
      email:
        recipients:
          - $EMAIL_DANIEL
        notify:
          success: true
          failure: true
      slack:
        channel: '#build-notifications'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
  ios-debug-build:
    name: Ios Debug Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - notification_emails
        - ripple_arc
      flutter: 3.29.2
    cache:
      cache_paths:
        - ~/.pub-cache
        - ios/Pods
        - $FLUTTER_ROOT/.pub-cache
        - /usr/local/Homebrew
    scripts:
      - name: Clone and Checkout
        script: |
          git clone "$CM_REPO_URL" .
          git checkout "$CM_COMMIT"

      - name: Install Dependencies
        script: |
          echo "Downloading Dependencies..."
          flutter pub get
      - name: Build Ios Debug
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - $EMAIL_DANIEL
        notify:
          success: true
          failure: true
      slack:
        channel: '#build-notifications'
        notify_on_build_start: true
        notify:
          success: true
          failure: true