name: construculator
description: "A calculator for construction workers"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.12.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: 1.0.9
  flutter_bloc: 9.1.1
  flutter_modular: 6.3.4
  supabase_flutter: 2.16.0
  flutter_dotenv: 6.0.1
  logger: 2.7.0
  stack_trace: 1.12.1
  equatable: 2.1.0
  rxdart: 0.28.0
  freezed_annotation: 3.1.0
  json_annotation: 4.9.0
  ripplearc_coreui: 0.11.0
  pinput: 6.0.2
  ripplearc_linter: 0.4.2
  async: 2.13.1
  intl: 0.20.2
  sentry_flutter: 9.24.0
  powersync: 1.18.0
  posthog_flutter: 5.35.1
  path_provider: 2.1.6
  path: 1.9.1
  package_info_plus: 10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.8
  build_runner: 2.15.1
  mutation_test: 1.8.0
  freezed: 3.2.3
  json_serializable: 6.11.2
  custom_lint: 0.8.1
  bloc_test: 10.0.0
  patrol: 4.9.0
  integration_test:
    sdk: flutter

patrol:
  app_name: Construculator
  test_directory: integration_test
  android:
    package_name: com.cms.cm_sample.fishfood
  ios:
    bundle_id: com.example.construculatorAppArchitecture

flutter:
  uses-material-design: true
  generate: true
  # TODO: [CA-831] [Chore] Migrate iOS build from CocoaPods to Swift Package Manager https://ripplearc.youtrack.cloud/issue/CA-831/Chore-Migrate-iOS-build-from-CocoaPods-to-Swift-Package-Manager
  config:
    enable-swift-package-manager: false

  assets:
    # Environment files
    - assets/env/
    - assets/icons/

flutter_native_splash:
  # iOS configuration
  image: "assets/icons/splash_icon.png"
  color: "#003A54"
  color_dark: "#003A54"

  branding: "assets/icons/branding.png"
  branding_dark: "assets/icons/branding.png"
  branding_mode: bottom
  branding_bottom_padding: 50

  # ios_content_mode: scaleAspectFit

  # Disable Android native splash (using custom AnimatedVectorDrawable instead)
  android: false
  ios: true
