name: Trigger Comprehensive Check
on:
  issue_comment:
    types: [created, edited]
jobs:
  trigger:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '#RunCheck')
    steps:
      - name: Extract PR Source Branch
        id: extract-branch
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_JSON=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")

          BRANCH_NAME=$(echo "$PR_JSON" | jq -r '.head.ref')
          echo "BRANCH: $BRANCH_NAME"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Trigger Codemagic on Source Branch
        env:
          CODEMAGIC_API_TOKEN: ${{ secrets.CODEMAGIC_API_TOKEN }}
          CODEMAGIC_APP_ID: ${{ secrets.CODEMAGIC_APP_ID }}
        run: |
          FULL_RESPONSE=$(curl -s \
            -X POST \
            -H "Content-Type: application/json" \
            -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            -d '{
              "appId": "'"$CODEMAGIC_APP_ID"'",
              "workflowId": "comprehensive-check",
              "branch": "'"${{ steps.extract-branch.outputs.branch_name }}"'",
              "environment": {
                "variables": {
                  "FORCE_FAIL": "false"
                }
              }
            }' \
            "https://api.codemagic.io/builds"
          )

          echo "Full API response: $FULL_RESPONSE"

      - name: Trigger iOS Debug Build on Source Branch
        env:
          CODEMAGIC_API_TOKEN: ${{ secrets.CODEMAGIC_API_TOKEN }}
          CODEMAGIC_APP_ID: ${{ secrets.CODEMAGIC_APP_ID }}
        run: |
          FULL_RESPONSE=$(curl -s \
            -X POST \
            -H "Content-Type: application/json" \
            -H "x-auth-token: $CODEMAGIC_API_TOKEN" \
            -d '{
              "appId": "'"$CODEMAGIC_APP_ID"'",
              "workflowId": "ios-debug-build",
              "branch": "'"${{ steps.extract-branch.outputs.branch_name }}"'",
              "environment": {
                "variables": {
                  "FORCE_FAIL": "false"
                }
              }
            }' \
            "https://api.codemagic.io/builds"
          )

          echo "Full API response: $FULL_RESPONSE"
